# Generated by Django 4.2.3 on 2023-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dota_id', models.CharField(blank=True, max_length=100, null=True)),
                ('winline_id', models.CharField(max_length=100)),
                ('twitch_id', models.JSONField(blank=True, default=dict, null=True)),
                ('tasks', models.JSONField(blank=True, default=dict, null=True)),
                ('current_task', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
